import Navbar from "@/components/ui/Navbar";
import "./globals.css";
import DataProvider from "@/components/provider/DataProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <DataProvider>
        <Navbar />
        {children}
      </DataProvider>
      </body>
    </html>
  );
}
